# Generated by Django 6.1.1 on 2026-09-22 09:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('memory', models.CharField(max_length=255, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('sale_price', models.CharField(max_length=255, null=True)),
                ('product_code', models.CharField(max_length=255, null=True)),
                ('reviews_count', models.IntegerField(null=True)),
                ('screen_diagonal', models.CharField(max_length=255, null=True)),
                ('screen_resolution', models.CharField(max_length=255, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500, null=True), null=True)),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('search_query', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(max_length=500, null=True)),
            ],
        ),
    ]
